package controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;

import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import dao.StudentDAOImpl;
import model.Student;

@WebServlet("/DownloadStudentPdfServlet")

public class DownloadStudentPdfServlet
extends HttpServlet {

    private static final long
    serialVersionUID = 1L;

    protected void doGet(

            HttpServletRequest request,

            HttpServletResponse response)

            throws ServletException,
            IOException {

        int id = Integer.parseInt(
                request.getParameter("id"));

        StudentDAOImpl dao =
                new StudentDAOImpl();

        Student s =
                dao.getStudentById(id);

        // PDF RESPONSE

        response.setContentType(
                "application/pdf");

        response.setHeader(

        "Content-Disposition",

        "attachment; filename=student_report.pdf");

        try {

            Document document =
                    new Document();

            PdfWriter.getInstance(

                    document,

                    response.getOutputStream());

            document.open();

            // TITLE

            Font titleFont =

            FontFactory.getFont(

                    FontFactory.HELVETICA_BOLD,

                    24);

            Paragraph title =

            new Paragraph(

            "Student Report",

            titleFont);

            title.setSpacingAfter(20);

            document.add(title);

            // IMAGE

            String imagePath =

            getServletContext()

            .getRealPath("/uploads/")
            + s.getPhoto();

            try {

                Image image =
                        Image.getInstance(
                                imagePath);

                image.scaleToFit(
                        120,
                        120);

                image.setSpacingAfter(20);

                document.add(image);

            } catch(Exception e) {

                e.printStackTrace();
            }

            // TABLE

            PdfPTable table =
                    new PdfPTable(2);

            table.setWidthPercentage(100);

            addRow(table,
                    "Student ID",
                    String.valueOf(
                            s.getId()));

            addRow(table,
                    "Name",
                    s.getName());

            addRow(table,
                    "Email",
                    s.getEmail());

            addRow(table,
                    "Phone",
                    s.getPhone());

            addRow(table,
                    "Course",
                    s.getCourse());

            addRow(table,
                    "Marks",
                    String.valueOf(
                            s.getMarks()));

            document.add(table);

            // FOOTER

            Paragraph footer =

            new Paragraph(

            "\n\nGenerated By Student Management System");

            document.add(footer);

            document.close();

        } catch(Exception e) {

            e.printStackTrace();
        }
    }

    // ADD ROW METHOD

    private void addRow(

            PdfPTable table,

            String key,

            String value) {

        PdfPCell cell1 =
                new PdfPCell(
                        new Paragraph(key));

        PdfPCell cell2 =
                new PdfPCell(
                        new Paragraph(value));

        table.addCell(cell1);

        table.addCell(cell2);
    }
}